apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpcservertest
    spec:
      containers:
      - name: grpc-server-test
        image: gokulraj18/grpcservertest:latest
        ports:
          - containerPort: 50051