apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcserver
  namespace: gr
  labels:
    app: grrpcserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grrpcserver
  template:
    metadata:
      labels:
        app: grpcserver
    spec:
      containers:
      - name: grpc-server-test
        image: gokulraj18/grpcservertest:latest
        ports:
          - containerPort: 50051